# Generated by Django 5.2.7 on 2025-11-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la receta"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(max_length=300, verbose_name="Descripción breve"),
                ),
                ("ingredientes", models.TextField(verbose_name="Ingredientes")),
                (
                    "instrucciones",
                    models.TextField(verbose_name="Instrucciones de preparación"),
                ),
                (
                    "tiempo_preparacion",
                    models.IntegerField(
                        default=30, verbose_name="Tiempo de preparación (minutos)"
                    ),
                ),
                (
                    "porciones",
                    models.IntegerField(default=4, verbose_name="Número de porciones"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recetas/",
                        verbose_name="Imagen de la receta",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
